name: "Build"

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
    branches:
      - main

env:
  JAVA_OPTS: -Xms1g -Xmx3g
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.configureondemand=true -Dorg.gradle.jvmargs=-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3.10.0
        with:
          distribution: 'zulu'
          java-version: 11

      # For watchOS x86 simulator. Remove with Kotlin 1.8.
      - uses: maxim-lobanov/setup-xcode@v1
        if: matrix.os == 'macos-latest'
        with:
          xcode-version: '13.4.1'

      - name: Build
        uses: gradle/gradle-build-action@v2.4.0
        with:
          arguments: build --scan --full-stacktrace

      - name: Bundle the build report
        if: failure()
        run: find . -type d -name 'reports' | zip -@ -r build-reports.zip

      - name: Upload the build report
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: error-report
          path: build-reports.zip

  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Dokka
        id: Dokka
        run: ./gradlew cleanDocs dokkaHtml

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto update docs

  publish:
    env:
      SONATYPE_USER: '${{ secrets.SONATYPE_USER }}'
      SONATYPE_PWD: '${{ secrets.SONATYPE_PWD }}'
      OSS_USER: '${{ secrets.OSS_USER }}'
      OSS_TOKEN: '${{ secrets.OSS_TOKEN }}'
      OSS_STAGING_PROFILE_ID: '${{ secrets.OSS_STAGING_PROFILE_ID }}'
      SIGNING_KEY_NAME: '${{ secrets.SIGNING_KEY_NAME }}'
      SIGNING_KEY_ID: '${{ secrets.SIGNING_KEY_ID }}'
      SIGNING_KEY_PASSPHRASE: '${{ secrets.SIGNING_KEY_PASSPHRASE }}'
      SIGNING_KEY: '${{ secrets.SIGNING_KEY }}'
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3.10.0
        with:
          distribution: 'zulu'
          java-version: 11

      # For watchOS x86 simulator. Remove with Kotlin 1.8.
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.4.1'

      - name: Publish to MavenCentral
        run: ./gradlew build publishToSonatype

      - name: Stop Gradle daemons
        run: ./gradlew --stop
