name: "Build main"

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

env:
  JAVA_OPTS: -Xms512m -Xmx1024m
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.configureondemand=true -Dorg.gradle.jvmargs=-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3.10.0
        with:
          distribution: 'zulu'
          java-version: 11

      # For watchOS x86 simulator. Remove with Kotlin 1.8.
      - uses: maxim-lobanov/setup-xcode@v1
        if: matrix.os == 'macos-latest'
        with:
          xcode-version: '13.4.1'

      - name: Build
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: build --scan --full-stacktrace

      - name: Bundle the build report
        if: failure()
        run: find . -type d -name 'reports' | zip -@ -r build-reports.zip

      - name: Upload the build report
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: error-report
          path: build-reports.zip
